### ISSUE TITLE
안녕하세요 ㅠ ㅠ

### ISSUE THREAD

**Issue by RNGP** [ChalkPE/ffxiv-opener-overlay#1]
우선 너무너무 좋은 것 공유해주셔서 감사합니다...
설명에 나와있는대로 오버레이 플러그인 설치 방법 gif 파일 올라온 것까지 확인하며 그대로 따라해 보았어용
그래서 오버레이에 지역 이동 해 달라는 문구 보고 지역이동해서 그 문구 없애는 데까지는 성공했는데 그 이후에 나무인형을 쳐도 스킬이 입력되지가 않아요 ;ㅅ; 혹 ACT 내에서 따로 설정해야하는 부분이 있다거나 한건지 여쭙고 싶습니다 흑흑

**Comment by chalkpe** [comment]
안녕하세요 확인이 늦어서 죄송합니다

### 오버레이가 `Log Parse` 형식인지 확인해주세요
![image](https://user-images.githubusercontent.com/9481405/53548695-80d27780-3b75-11e9-82bb-1e5d12f5009c.png)

### 전투 로그를 확인해주세요
로그에 `초크가 말레피가를 시전했습니다.`와 같은 메세지가 떠야 합니다. 이 메세지로 스킬 사용을 인식하는 거라 꺼져 있으면 작동이 안 돼요!

![image](https://user-images.githubusercontent.com/9481405/53548161-33a1d600-3b74-11e9-9fae-ef932127e52a.png)

**캐릭터 설정 (K)** -> **대화창 설정** -> **로그 필터 설정** 메뉴에서 **자신의 기술 시작 및 중단**이 켜진 게 하나라도 존재하는지 확인해 주세요

![image](https://user-images.githubusercontent.com/9481405/53548275-7499ea80-3b74-11e9-8a7c-1be447590cf3.png)
