### ISSUE TITLE
Unable to recognize non "cast" abilities

### ISSUE THREAD

**Issue by hikarin-dev** [ChalkPE/ffxiv-opener-overlay#2]
![image](https://user-images.githubusercontent.com/19721540/64923185-167bde80-d80a-11e9-8561-99c430eb907d.png)

It seems to not recognize non-cast abilities "You use <skill name>." and only "You cast <skill name>".

**Comment by chalkpe** [comment]
Fixed in v0.2.1 😃 

 ![image](https://user-images.githubusercontent.com/9481405/64932404-ae64e100-d879-11e9-84a3-f07a59c5a5f9.png)
