### ISSUE TITLE
Log Parse type not available?

### ISSUE THREAD

**Issue by MarkusWo** [ChalkPE/ffxiv-opener-overlay#27]
I am wondering if I am using the wrong OverlayPlugin (I'm using ngld) or whether I am missing something but I cannot find a "Log Parser" when creating a new Overlay. How do I find it, what do I choose?

![Log Parse](https://user-images.githubusercontent.com/17179276/149625275-bc13fe5d-491b-4d33-a3d2-8d54bc8c4a38.jpg)

**Comment by chalkpe** [comment]
Scroll down `Voreinstellung` list (`Preset` in English) and select last item `Custom`. Then you will see the `Type` options, maybe default value set to `MiniParse` so you don't need to touch about that.
And sorry for late reply, figured out that the description on README is outdated. I'll update it with ngld version of OverlayPlugin. Thanks!

**Comment by chalkpe** [comment]
![image](https://user-images.githubusercontent.com/9481405/153808850-c8ad5131-32ab-4771-8aa5-3ec964fff67b.png)
